apiVersion: apps/v1beta2
kind: Deployment
metadata:
    name: adminportal-development
spec:
  selector: 
   matchLabels:
      app: adminportalweb
  replicas: 2 

  template:
    metadata: 
     labels:
       app: adminportalweb
    spec:
      containers: 
      - name: adminportalweb
        image: darshanadinushal/adminportalclientapp
        ports:
        - containerPort: 80 

---
apiVersion: v1
kind: Service
metadata:
    name: adminportal-service
spec: 
  selector: 
    app: adminportalweb
  ports:
    - port: 80
  type: LoadBalancer
