apiVersion: apps/v1beta2
kind: Deployment
metadata:
    name: adminportal-development
spec:
  selector: 
   matchLabels:
      app: adminportalweb
  replicas: 2 

  template:
    metadata: 
     labels:
       app: adminportalweb
    spec:
      containers: 
      - name: adminportalweb
        image: darshanadinushal/adminportalclientapp
        ports:
        - containerPort: 8000 

---
apiVersion: v1
kind: Service
metadata:
  labels: #PODS
    app: adminportal-Service
  name: adminportal-Service
  namespace: default
spec:
  ports:
  - # nodePort: 30702 #CHANGE
    port: 8000 #CHANGE
    protocol: TCP
    targetPort: 8000 #CHANGE
  selector:
    app: adminportalweb
  sessionAffinity: None #CHANGE
  type: LoadBalancer